### ISSUE TITLE
Apres personalisation  les sensors deviennent indisponibles

### ISSUE THREAD

**Issue by jblb** [kamaradclimber/rte-ecowatt#1]
Voila le problème que je rencontre si je veux personnaliser une entree de l'intégration rte_ecowatt
Dans une carte de type entities, sélectionner un capteur, dans l'onglet paramètre changer le nom ou l’icône et valider: le capteur devient indisponible. pas d'erreur particulière dans les logs d'HA.
Si on redémarre HA, le capteur est a nouveau disponible avec son nouveau nom.

**Comment by brenard** [comment]
Étrange, j'ai une carte du même type avec la même personalisation et j'ai pas de soucis : 
``` yaml
type: entities
entities:
  - entity: sensor.ecowatt_level_now
    name: Actuellement
    icon: mdi:lightning-bolt-circle
  - entity: sensor.ecowatt_level_today
    name: Aujourd'hui
    icon: mdi:lightning-bolt-circle
  - entity: sensor.ecowatt_level_tomorrow
    name: Demain
    icon: mdi:lightning-bolt-circle
  - entity: sensor.ecowatt_level_in_2_days
    name: Après-demain
    icon: mdi:lightning-bolt-circle
  - entity: sensor.ecowatt_level_in_3_days
    name: Dans 3 jours
    icon: mdi:lightning-bolt-circle
title: Ecowat
```
